"""add new columns in campaign model

Revision ID: 448fd3b4deeb
Revises: bfef6459c937
Create Date: 2026-03-19 15:29:24.894503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448fd3b4deeb'
down_revision: Union[str, Sequence[str], None] = 'bfef6459c937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('main_quest', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('villain', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('action_count', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'status')
    op.drop_column('campaigns', 'action_count')
    op.drop_column('campaigns', 'villain')
    op.drop_column('campaigns', 'main_quest')
    # ### end Alembic commands ###
