"""add health column

Revision ID: 939ae9c7e7c0
Revises: 9b231875556b
Create Date: 2026-03-16 01:51:37.124664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939ae9c7e7c0'
down_revision: Union[str, Sequence[str], None] = '9b231875556b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('health', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'health')
    # ### end Alembic commands ###
