"""add missing tables

Revision ID: bfef6459c937
Revises: 939ae9c7e7c0
Create Date: 2026-03-18 19:33:10.699640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfef6459c937'
down_revision: Union[str, Sequence[str], None] = '939ae9c7e7c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('characters', 'char_class',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'characters', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='unique')
    op.alter_column('characters', 'char_class',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('characters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
